# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongodb12_data:/data/db
    healthcheck:
      test: mongo -u root -p example --quiet --eval "db.adminCommand('ping').ok" | grep 1
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s

  webapp:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
          
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "4000:4000"


volumes:
  mongodb12_data: 